language: python
install:
  - travis_retry pip install tox==1.6.1
script:
  - export AUTH_URL=$AUTH_URL
  - export AUTH_TENANT=$AUTH_TENANT
  - export AUTH_USER_NAME=$AUTH_USER_NAME
  - export AUTH_API_KEY=$AUTH_API_KEY
  - export TOXENV=py27
  - tox
